### ISSUE TITLE
Add recursive directory iteration

### ISSUE THREAD

**Issue by McTwist** [bansheerubber/eggscript#1]
Add the ability to recursively iterate a directory for `.egg` files. A flag is also an option.

**Comment by bansheerubber** [comment]
this should be possible by supplying the directory like ```eggscript -o ./example_output ./example_directory/```. all ```.egg``` files found in ./example_directory/**/* will be transpiled and outputed to the ./example_output, while keeping ./example_directory's structure intact (folders will be created in ./example_output as needed)

**Comment by McTwist** [comment]
Why not recursively walk through each directory? You just have to check if the item is a directory and walk through that.

**Comment by bansheerubber** [comment]
[```os.walk(directory)``` handles the recursive part for you](https://stackoverflow.com/a/10989155). the way to think about it is it flattens the stuff it finds into an array of the tuples ```(root_directory, subdirectories, files)```. i've been able to transpile my own projects with complex directory structures using this

**Comment by McTwist** [comment]
Sure, I didn't realize that.
